require 'rake/testtask'
require 'rubygems'
require 'rspec/core/rake_task'

task :default => [:test]

task :install do
    exec "gem install right_api_client"
    exec "gem install right_aws"
end

Rake::TestTask.new do |t|
    t.libs << "test"
    t.test_files = FileList['*test.rb']
    t.verbose = true
end

RSpec::Core::RakeTask.new(:spec, :args) do |t, args|
    t.pattern = FileList['*_spec.rb']
end