require 'rubygems'
require 'rspec/core/rake_task'
require 'bundler/setup'

Bundler.require

task :default => [:spec]

RSpec::Core::RakeTask.new(:spec, :args) do |t, args|

    t.pattern = FileList['*_spec.rb']
end
